name: Run test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check out njs 
        uses: actions/checkout@v3
        with:
          name: nginx/njs
          ref: 0.7.9
      - run: |
        cd njs;
        ./configure;
        make;
        echo "${pwd}/build" >> $GITHUB_PATH ;
      - run: npm ci
      - run: npm test