name: Run test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 4141done/njs-test-runner:1.23.2_0.7.9
    steps:
      - uses: actions/checkout@v3
      - run: source $HOME/.bashrc && npm ci
      - run: source $HOME/.bashrc && npm test
